services:
  postgres:
    image: postgres:16-alpine
    container_name: shortlink-postgres
    environment:
      POSTGRES_DB: shortlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - shortlink_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: shortlink-redis
    ports:
      - "6379:6379"
volumes:
  shortlink_postgres_data: